# Generated by Django 4.1.2 on 2022-12-10 13:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_posting_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
