# Generated by Django 4.1.2 on 2022-12-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_posting_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('date', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Posting',
            },
        ),
    ]
