# Generated by Django 4.1.2 on 2022-12-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={},
        ),
    ]
