# Generated by Django 4.1.2 on 2022-12-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biodata',
            options={'verbose_name_plural': 'Biodata'},
        ),
    ]
